services:
    avro_csv.reader:
        class: Avro\CsvBundle\Util\Reader

    avro_csv.csv.form.type:
        class: Avro\CsvBundle\Form\Type\CsvFormType
        tags: 
            - { name: form.type, alias: avro_csv_csv }
       
    avro_csv.csv.form:
        factory_method: createNamed 
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@avro_csv.csv.form.type", avro_csv_csv]

    avro_csv.csv.form.handler:
        class: Avro\CsvBundle\Form\Handler\CsvFormHandler
        scope: request
        arguments: ["@avro_csv.csv.form", "@request", "@avro_csv.reader"]



