services:
    avro_csv.importer:
        class: Avro\CsvBundle\Doctrine\Importer
        arguments: ["@avro_csv.reader", "@event_dispatcher", "@avro_case.converter", "@doctrine.orm.entity_manager", "%avro_csv.batch_size%"]

